import { AuthProvider } from "./(provider)/authProvider";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CategoryProvider } from "./(provider)/categoryProvider";
import { ListProvider } from "./(provider)/listProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="w-screen h-screen">
        <AuthProvider>
          <CategoryProvider>
            <ListProvider>{children}</ListProvider>
          </CategoryProvider>{" "}
        </AuthProvider>
      </body>
    </html>
  );
}
